import { Product, Category, Origin, Brand } from "@/types/product";

// Mock Categories
export const categories: Category[] = [
    {
        id: "air-filter",
        name: "Lọc gió Động cơ - Air Filter",
    },
    {
        id: "fuel-filter",
        name: "Lọc Nhiên Liệu - Fuel Filter",
    },
    {
        id: "oil-filter",
        name: "Bộ lọc dầu",
    },
    {
        id: "uncategorized",
        name: "Chưa phân loại",
    },
    {
        id: "other",
        name: "Khác",
    },
];

// Mock Origins
export const origins: Origin[] = [
    {
        id: "germany",
        name: "Đức",
    },
    {
        id: "japan",
        name: "Nhật Bản",
    },
    {
        id: "china",
        name: "Trung Quốc",
    },
];

// Mock Brands
export const brands: Brand[] = [
    {
        id: "asakashi",
        name: "Asakashi",
    },
    {
        id: "bosch",
        name: "Bosch",
    },
    {
        id: "hyundai",
        name: "Hyundai",
    },
];

// Mock Products
export const products: Product[] = [
    {
        id: "1",
        image: "/product/bo_loc_khong_khi.png",
        isOnSale: true,
        title: "Lọc gió động cơ Bosch F026400123",
        price: 250000,
        originalPrice: 300000,
        discountPercentage: "17%",
        category_id: "air-filter",
        created_at: new Date("2024-01-15"),
        brand_id: "bosch",
        manufacturingYear: 2021,
        origin_id: "germany",
    },
    {
        id: "2",
        image: "/product/bo_loc_nhien_lieu.png",
        isOnSale: true,
        title: "Lọc nhiên liệu Asakashi FC-123",
        price: 560000,
        originalPrice: 220000,
        discountPercentage: "18%",
        category_id: "fuel-filter",
        created_at: new Date("2024-01-10"),
        brand_id: "asakashi",
        manufacturingYear: 2020,
        origin_id: "japan",
    },
    {
        id: "3",
        image: "/product/bo_loc_dau.png",
        isOnSale: false,
        title: "Bộ lọc dầu Hyundai 26300-35503",
        price: 150000,
        originalPrice: 150000,
        discountPercentage: "0%",
        category_id: "oil-filter",
        created_at: new Date("2024-01-08"),
        brand_id: "hyundai",
        manufacturingYear: 2019,
        origin_id: "china",
    },
    {
        id: "4",
        image: "/product/bo_loc_trong_cabin.png",
        isOnSale: true,
        title: "Lọc gió cabin Bosch 1987432123",
        price: 320000,
        originalPrice: 400000,
        discountPercentage: "20%",
        category_id: "air-filter",
        created_at: new Date("2024-01-05"),
        brand_id: "bosch",
        manufacturingYear: 2021,
        origin_id: "germany",
    },
    {
        id: "5",
        image: "/product/bo_loc_khong_khi.png",
        isOnSale: false,
        title: "Lọc nhiên liệu Asakashi FC-456",
        price: 200000,
        originalPrice: 200000,
        discountPercentage: "0%",
        category_id: "fuel-filter",
        created_at: new Date("2024-01-03"),
        brand_id: "asakashi",
        manufacturingYear: 2020,
        origin_id: "japan",
    },
    {
        id: "6",
        image: "/product/bo_loc_nhien_lieu.png",
        isOnSale: true,
        title: "Bộ lọc dầu Hyundai 26300-35504",
        price: 120000,
        originalPrice: 160000,
        discountPercentage: "25%",
        category_id: "oil-filter",
        created_at: new Date("2024-01-01"),
        brand_id: "hyundai",
        manufacturingYear: 2018,
        origin_id: "china",
    },
    {
        id: "7",
        image: "/product/bo_loc_dau.png",
        isOnSale: false,
        title: "Lọc gió động cơ Asakashi AF-789",
        price: 280000,
        originalPrice: 280000,
        discountPercentage: "0%",
        category_id: "air-filter",
        created_at: new Date("2023-12-28"),
        brand_id: "asakashi",
        manufacturingYear: 2021,
        origin_id: "japan",
    },
    {
        id: "8",
        image: "/product/bo_loc_trong_cabin.png",
        isOnSale: true,
        title: "Lọc nhiên liệu Bosch F026402456",
        price: 350000,
        originalPrice: 420000,
        discountPercentage: "17%",
        category_id: "fuel-filter",
        created_at: new Date("2023-12-25"),
        brand_id: "bosch",
        manufacturingYear: 2021,
        origin_id: "germany",
    },
    {
        id: "9",
        image: "/product/bo_loc_khong_khi.png",
        isOnSale: false,
        title: "Bộ lọc dầu Asakashi OF-321",
        price: 170000,
        originalPrice: 170000,
        discountPercentage: "0%",
        category_id: "oil-filter",
        created_at: new Date("2023-12-20"),
        brand_id: "asakashi",
        manufacturingYear: 2019,
        origin_id: "japan",
    },
    {
        id: "10",
        image: "/product/bo_loc_nhien_lieu.png",
        isOnSale: true,
        title: "Lọc gió cabin Hyundai 97133-2E250",
        price: 240000,
        originalPrice: 300000,
        discountPercentage: "20%",
        category_id: "air-filter",
        created_at: new Date("2023-12-18"),
        brand_id: "hyundai",
        manufacturingYear: 2020,
        origin_id: "china",
    },
    {
        id: "11",
        image: "/product/bo_loc_dau.png",
        isOnSale: false,
        title: "Lọc nhiên liệu Hyundai 31112-1G000",
        price: 190000,
        originalPrice: 190000,
        discountPercentage: "0%",
        category_id: "fuel-filter",
        created_at: new Date("2023-12-15"),
        brand_id: "hyundai",
        manufacturingYear: 2018,
        origin_id: "china",
    },
    {
        id: "12",
        image: "/product/bo_loc_trong_cabin.png",
        isOnSale: true,
        title: "Bộ lọc dầu Bosch F026407123",
        price: 220000,
        originalPrice: 280000,
        discountPercentage: "21%",
        category_id: "oil-filter",
        created_at: new Date("2023-12-12"),
        brand_id: "bosch",
        manufacturingYear: 2021,
        origin_id: "germany",
    },
];
